//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoveOrderDetail
    {
        public int ID { get; set; }
        public string SnNum { get; set; }
        public int OrderNum { get; set; }
        public string ProductName { get; set; }
        public string BarCode { get; set; }
        public string ProductNum { get; set; }
        public string BatchNum { get; set; }
        public double Num { get; set; }
        public Nullable<double> InPrice { get; set; }
        public Nullable<double> Amout { get; set; }
        public int IsPick { get; set; }
        public double RealNum { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int StorageNum { get; set; }
        public Nullable<int> FromLocalNum { get; set; }
        public Nullable<int> ToLocalNum { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual MoveOrder MoveOrder { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
