//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.MoveOrder = new HashSet<MoveOrder>();
            this.OutStorage = new HashSet<OutStorage>();
            this.ReturnDetail = new HashSet<ReturnDetail>();
            this.ReturnOrder = new HashSet<ReturnOrder>();
        }
    
        public int ID { get; set; }
        public string SnNum { get; set; }
        public string BarCode { get; set; }
        public string ProductName { get; set; }
        public double Num { get; set; }
        public double MinNum { get; set; }
        public double MaxNum { get; set; }
        public string UnitNum { get; set; }
        public string UnitName { get; set; }
        public string CateNum { get; set; }
        public string CateName { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public double InPrice { get; set; }
        public double OutPrice { get; set; }
        public double AvgPrice { get; set; }
        public double NetWeight { get; set; }
        public double GrossWeight { get; set; }
        public string Description { get; set; }
        public string PicUrl { get; set; }
        public int IsDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
        public int StorageNum { get; set; }
        public int DefaultLocal { get; set; }
        public string CusNum { get; set; }
        public string CusName { get; set; }
        public string Display { get; set; }
        public string Remark { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoveOrder> MoveOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutStorage> OutStorage { get; set; }
        public virtual Storage Storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnDetail> ReturnDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnOrder> ReturnOrder { get; set; }
    }
}
